config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, reverse_lazy
from employees.views import DashboardView
from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',DashboardView.as_view(), name='dashboard'),

    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='registration/login.html',
        authentication_form=LoginForm,
        redirect_authenticated_user=True,
    ), name='login'),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.txt',
        html_email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
        success_url=reverse_lazy('password_reset_done'),
    ), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('password_reset_complete'),
    ), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('employees/', include('employees.urls')),
    # path('', include('enrollments.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('modalities.urls')),
    # path('', include('students.urls'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/urls.py
from django.urls import path
from .views import (
    EmployeeListView,
    EmployeeCreateView,
    EmployeeUpdateView,
    EmployeeDeleteView,
    EmployeeDetailView,
    EmployeePermissionsUpdateView
)

app_name = 'employees'

urlpatterns = [
    path('', EmployeeListView.as_view(), name='list'),
    path('new/', EmployeeCreateView.as_view(), name='create'),
    path('view/<int:pk>/', EmployeeDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', EmployeeUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', EmployeeDeleteView.as_view(), name='delete'),
    path('permissions/<int:pk>/', EmployeePermissionsUpdateView.as_view(), name='permissions'),
]

modalities/urls.py
from django.urls import path
from .views import *

app_name = "modalities"

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("categories/new/", CategoryCreateView.as_view(), name="category_create"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category_update"),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),
    path("sub-categories/", SubCategoryListView.as_view(), name="sub_category_list"),
    path("sub-categories/new/", SubCategoryCreateView.as_view(), name="sub_category_create"),
    path("sub-categories/<int:pk>/edit/", SubCategoryUpdateView.as_view(), name="sub_category_update"),
    path('sub-categories/<int:pk>/', SubCategoryDetailView.as_view(), name='sub_category_detail'),
    path("sub-categories/<int:pk>/delete/", SubCategoryDeleteView.as_view(), name="sub_category_delete"),
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("groups/", GroupListView.as_view(), name="group_list"),
    path("groups/new/", GroupCreateView.as_view(), name="group_create"),
    path("groups/<int:pk>/edit/", GroupUpdateView.as_view(), name="group_update"),
    path("groups/<int:pk>/delete/", GroupDeleteView.as_view(), name="group_delete"),
    path('groups/<int:pk>/', GroupDetailView.as_view(), name='group_detail'),
]

templates/base.html
{% load static %}
<!doctype html>
<html class="fixed">
	<head>
		<!-- Basic -->
		<meta charset="UTF-8">
		<title>{% block title %}{% endblock %}</title>
		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">
		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<!-- Web Fonts  -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
		<!-- Vendor CSS -->
        <link rel="stylesheet" href="{% static 'administration/vendor/bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'administration/vendor/animate/animate.compat.css' %}">
        <link rel="stylesheet" href="{% static 'administration/vendor/font-awesome/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'administration/vendor/boxicons/css/boxicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'administration/vendor/magnific-popup/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'administration/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css' %}">
		<!-- Theme CSS -->
        <link rel="stylesheet" href="{% static 'administration/css/theme.css' %}">
		<!-- Skin CSS -->
        <link rel="stylesheet" href="{% static 'administration/css/skins/default.css' %}">
        {% block extra_css %}{% endblock %}
		<!-- Theme Custom CSS -->
        <link rel="stylesheet" href="{% static 'administration/css/custom.css' %}">
		<!-- Head Libs -->
        <script src="{% static 'administration/vendor/modernizr/modernizr.js' %}" defer></script>
	</head>
	<body>
		<section class="body">
			<!-- start: header -->
			<header class="header">
				<div class="logo-container">
					<a href="{% url "dashboard" %}" class="logo">
						<img src="{% static 'administration/img/logo_aula_286.png' %}" width="75" height="35" alt="Porto Admin" />
					</a>
					<div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fas fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>
				<!-- start: search & user box -->
				<div class="header-right">
					<span class="separator"></span>
					<div id="userbox" class="userbox">
						<a href="#" data-bs-toggle="dropdown">
							<div class="profile-info">
								<span class="name">{{ user.get_full_name|default:user.email }}</span>
							</div>
							<i class="fa custom-caret"></i>
						</a>
						<div class="dropdown-menu">
							<ul class="list-unstyled mb-2">
								<li class="divider"></li>
								<li>
									<a id="btn_logout" href="#"><i class="bx bx-power-off"></i> Salir</a>
									<form id="logout-form" action="{% url "logout" %}" method="post" style="display:none;">
										{% csrf_token %}
										<button type="submit"></button>
									  </form>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- end: search & user box -->
			</header>
			<!-- end: header -->
			<div class="inner-wrapper">
				<!-- start: sidebar -->
				<aside id="sidebar-left" class="sidebar-left">
				    <div class="sidebar-header">
				        <div class="sidebar-title">
				            Navegación
				        </div>
				        <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
				            <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
				        </div>
				    </div>
				    <div class="nano">
				        <div class="nano-content">
				            <nav id="menu" class="nav-main" role="navigation">
				                <ul class="nav nav-main">
									<li class="{% if active_menu == 'employees' %}nav-active{% endif %}">
                              			<a class="nav-link" href="{% url "employees:list" %}">
                                			<span>Empleados</span>
                              			</a>                        
                            		</li>
                            		<li class="{% if active_menu == 'groups' %}nav-active{% endif %}">
										<a class="nav-link" href="{% url "users:group_list" %}">
								  			<span>Grupos</span>
										</a>                        
							  		</li>
							  		<li class="{% if active_menu == 'categories' %}nav-active{% endif %}">
										<a class="nav-link" href="{% url "modalities:category_list" %}">
								  			<span>Categorías</span>
										</a>                        
							  		</li>
							  		<li class="{% if active_menu == 'subcategories' %}nav-active{% endif %}">
										<a class="nav-link" href="{% url "modalities:sub_category_list" %}">
								  			<span>Sub categorías</span>
										</a>                        
							  		</li>
				                </ul>
				            </nav>
				        </div>
				        <script>
				            // Maintain Scroll Position
				            if (typeof localStorage !== 'undefined') {
				                if (localStorage.getItem('sidebar-left-position') !== null) {
				                    var initialPosition = localStorage.getItem('sidebar-left-position'),
				                        sidebarLeft = document.querySelector('#sidebar-left .nano-content');

				                    sidebarLeft.scrollTop = initialPosition;
				                }
				            }
				        </script>
				    </div>
				</aside>
				<!-- end: sidebar -->
				<section role="main" class="content-body">
					<header class="page-header">
						<h2>{% block page_header %}{% endblock %}</h2>
						<div class="right-wrapper text-end">
							<ol class="breadcrumbs">
								<li>
									<a href="{% url "dashboard" %}">
										<i class="bx bx-home-alt"></i>
									</a>
								</li>
                                {% block breadcrumbs %}{% endblock %}
							</ol>
							<a class="sidebar-right-toggle" style="cursor: auto;"></a>
						</div>
					</header>
					<!-- start: page -->
                    {% block content %}{% endblock %}
					<!-- end: page -->
				</section>
			</div>
		</section>
		<!-- Vendor -->
        <script src="{% static 'administration/vendor/jquery/jquery.js' %}" defer></script>
        <script src="{% static 'administration/vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}" defer></script>
        <script src="{% static 'administration/vendor/popper/umd/popper.min.js' %}" defer></script>
        <script src="{% static 'administration/vendor/bootstrap/js/bootstrap.bundle.min.js' %}" defer></script>
        <script src="{% static 'administration/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}" defer></script>
		<script src="{% static 'administration/vendor/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}" defer></script>
        <script src="{% static 'administration/vendor/common/common.js' %}" defer></script>
        <script src="{% static 'administration/vendor/nanoscroller/nanoscroller.js' %}" defer></script>
        <script src="{% static 'administration/vendor/magnific-popup/jquery.magnific-popup.js' %}" defer></script>
        <script src="{% static 'administration/vendor/jquery-placeholder/jquery.placeholder.js' %}" defer></script>
		<!-- Specific Page Vendor -->
        {% block extra_js %}{% endblock %}
		<!-- Theme Base, Components and Settings -->
        <script src="{% static 'administration/js/theme.js' %}" defer></script>
		<!-- Theme Custom -->
        <script src="{% static 'administration/js/custom.js' %}" defer></script>
		<!-- Theme Initialization Files -->
        <script src="{% static 'administration/js/theme.init.js' %}" defer></script>
		<script>
			// jQuery required

		  </script>
	</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block content %}
  <h1>Dashboard</h1>
  <p>Total de empleados registrados: <strong>{{ total_empleados }}</strong></p>

  <p>
    <a href="{% url 'employees:list' %}">Ver empleados</a>
    {% if user.is_staff %}
        <a href="/admin/">Ir al admin</a>
    {% endif %}
  </p>
{% endblock %}